add api/reviews to the project
Mycroftd/david_nc_games pull request #3
Opened 2022-12-12 15:38 UTC by Mycroftd

2022-12-12 15:58 UTC, johnhutcheon requested changes
Hi David. It looks like you've just missed the 'comment_count' property which is required for this ticket, if you could look over the Trello board for this one again. If you could resubmit with the changes in the comments please, that would be great 👍

2022-12-12 15:58 UTC, johnhutcheon commented on __tests__/app.test.js
> +                    votes: expect.any(Number),
This is missing the 'owner' and 'comment_count' properties as specified on Trello ticket 4. Could you please add these?

2022-12-12 15:58 UTC, johnhutcheon commented on models/games.model.js
> +  return db.query("SELECT * FROM reviews ORDER BY created_at DESC;").then((reviews) => {
This needs to take into account the 'comment_count' property which is specified on the ticket.

2022-12-13 11:09 UTC, MRombi approved these changes
Good job David, delete that console log and you are good to merge 😄

2022-12-13 11:09 UTC, MRombi commented on controllers/games.controller.js
> +    console.log(reviews);
We should delete all the console.logs 🙂

2022-12-13 11:16 UTC, merged